# Generated by Django 4.2.7 on 2023-11-02 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_fname', models.CharField(max_length=200, verbose_name='First Name')),
                ('emp_lname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('emp_email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('emp_position', models.CharField(max_length=200, verbose_name='Position')),
                ('pub_date', models.DateField(default=datetime.datetime(2023, 11, 2, 2, 1, 39, 300118, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
