# Generated by Django 4.2.7 on 2023-11-02 03:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee_emp_image_alter_employee_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 2, 3, 8, 29, 659661, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='null', max_length=254)),
                ('body', models.TextField(default='null')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2023, 11, 2, 3, 8, 29, 659661, tzinfo=datetime.timezone.utc))),
                ('active', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.employee')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
