# Generated by Django 4.2.7 on 2023-11-10 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_comment_created_on_alter_employee_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 21, 54, 24, 372566, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 10, 21, 54, 24, 372566, tzinfo=datetime.timezone.utc)),
        ),
    ]
