# Generated by Django 4.2.7 on 2023-11-11 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_comment_created_on_alter_employee_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 0, 51, 43, 540852, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 11, 0, 51, 43, 540852, tzinfo=datetime.timezone.utc)),
        ),
    ]
