# Generated by Django 4.2.7 on 2023-11-17 07:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_employee_contact_number_alter_comment_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 7, 40, 43, 542057, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 17, 7, 40, 43, 542057, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(default='', max_length=255, verbose_name='Street Address')),
                ('city', models.CharField(default='', max_length=100, verbose_name='City')),
                ('state', models.CharField(default='', max_length=100, verbose_name='State')),
                ('zip_code', models.CharField(default='', max_length=20, verbose_name='ZIP Code')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='users.employee')),
            ],
        ),
    ]
