# Generated by Django 4.2.7 on 2023-11-17 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_employee_previous_salary_alter_comment_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='previous_salary',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 8, 9, 31, 432342, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 17, 8, 9, 31, 432342, tzinfo=datetime.timezone.utc)),
        ),
    ]
