# Generated by Django 4.2.7 on 2023-11-24 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_employee_birthday_alter_comment_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave')], default='active', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 8, 41, 24, 880797, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 8, 41, 24, 880797, tzinfo=datetime.timezone.utc)),
        ),
    ]
